### ISSUE TITLE
Update dependency of Bangbang.jl to v0.4

### ISSUE THREAD

**Issue by PhyX-Meow** [JuliaFolds/FLoops.jl#132]
It prevents me to update Transducers.jl to latest version. Thank you!

**Comment by PhyX-Meow** [comment]
https://github.com/JuliaFolds/FLoops.jl/pull/133

**Comment by MasonProtter** [comment]
Hi @PhyX-Meow, sorry for the delay, this is now completed in https://github.com/JuliaFolds2/FLoops.jl (note the 2!) 

JuliaFolds packages are all migrating to JuliaFolds2 unfortunately.
